{
 "title": "Main dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "exchange-api-1, exchange-api-2, exchange-api-3, exchange-cadvisor-1, exchange-grafana-1, exchange-graphite-1,  exchange-nginx-1, exchange_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "USD Volume over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.usd.volume.total), 'USD Total por intervalo')"
    }
   ]
  },
  {
   "title": "USD Net over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.usd.volume.net), 'USD Net por intervalo')"
    }
   ]
  },
  {
   "title": "EUR Volume over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.eur.volume.total), 'EUR Total por intervalo')"
    }
   ]
  },
  {
   "title": "EUR Net over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.eur.volume.net), 'EUR Net por intervalo')"
    }
   ]
  },
  {
   "title": "ARS Volume over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.ars.volume.total), 'ARS Total por intervalo')"
    }
   ]
  },
  {
   "title": "ARS Net over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.ars.volume.net), 'ARS Net por intervalo')"
    }
   ]
  },
  {
   "title": "BRL Volume over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.brl.volume.total), 'BRL Total por intervalo')"
    }
   ]
  },
  {
   "title": "BRL Net over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.arvault.brl.volume.net), 'BRL Net por intervalo')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 34359738368), 'Memory')"
    }
   ]
  }
 ]
}